package deck

// WAS GENERATED BY PUTTING //go:generate stringer -type=CardColor IN CARD.GO
// HAD A TYPO ON LINE 20; REMOVED go:generate COMMENT AND EDITED THIS FILE.

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Red-5]
	_ = x[Black-6]
}

const _CardColor_name = "RedBlack"

var _CardColor_index = [...]uint8{0, 3, 8}

func (i CardColor) String() string {
	//i -= 5  // COMMENTING OUT THIS LINE WAS AN EDIT TO THIS AUTO GENERATED FILE.
	// WAS STOPPING PROPER FUNCTIONING OF THIS FUNCTION!
	if i < 0 || i >= CardColor(len(_CardColor_index)-1) {
		return "CardColor(" + strconv.FormatInt(int64(i+5), 10) + ")"
	}
	return _CardColor_name[_CardColor_index[i]:_CardColor_index[i+1]]
}
